dist: trusty
sudo: required
language: node_js
node_js:
  - node
branches:
  except:
  - gh-pages
notifications:
  email: false
services:
  - docker

jobs:
  include:
    - stage: Build
      name: "Build Docker Images"
      install: cd scripts && npm ci && cd ..
      script: node scripts/build
      env:
        # DEPLOY_SETTINGS_JSON='{"CI":[{"type":"docker","options":{"user":"","pass":""}}]}'
        - secure: PU5LQoySgtWN3wLRc/pHkhpOej2PQDL5Mv+xtoMYgdi9W9V3xBCyjtseKtJ+ZmDAR/jbQGyLQMWiHADTQcRpXS5kIj/e1rYw3VIJgVNxVee7mCjo3y+0ukQ0PszDeOZV9qSC80t2kyKUK0piWBZtedjaQw04ofOsS+Hdx1JijwcxG2fcCM1zCuSudotN/dAtnx/qLie72bdqhO28WEKGGjg/nLriwm3fYR+en2/z6u3BGhP0cUWCyI/fh9M0xKUNNVgjI/UBWfM9F0M/fqapx+CuMKWAFhUkj7dwhNVoEpYk4k7ffnj3OKJ9wQHkQ6RVqyr6JODwa8/G3rEnulkPeU+SP5T0qm2gUmuz6uyKFGi0PBTmWki1hmCOIffx6N20nXOJUAWb5JNl/IVH1MHuCI5hUR3Ek0mU6LzaQcre4hNzUGD7IahEep+mTXFZPrVNFRLoVhSQZFP1mXAKQYM5d6nwHxxgO/nMvsxTYfj8/y4Ic2OI9ruqgGjTyafPAbVZBm/V86J1qd1H4e7CREWOuHmS6l3yvkx2Avn/Qyk0pmzYPk4KYZESSWI++Y8DQEuI43u8lHpV1jpoclYzPmcXJHsb5KKQVNimT7eTc0dZUQWkZ9bTnfnTPW4CzpXotFYLU3TW+piylkg7sUMeCmMV7ypjVbwFA3bI0LKtWgOk+uo=

    - stage: Test
      name: "Unit Tests"
      env:
        - image_tag=peyk/federation:unstable-solution
      script: echo ToDo

    - stage: Deploy
      name: "Deploy"
      script: skip
      install:
        - cd scripts && npm ci && cd ..
        - docker pull peyk/federation:unstable
      env:
        # DEPLOY_SETTINGS_JSON='{"Production":[
        #   {"type":"docker","options":{"source":"peyk/federation:unstable","target":"peyk/federation","user":"","pass":""}},
        #   {"type":"heroku","options":{"app":"peyk-federation","source":"peyk/federation","dyno":"web","user":"","token":""}}
        # ]}'
        - secure: LRKotOb96HcopYl9ASZx/jj4iVdt1TPnSGvHLn3PJ9MKJLLbhudtpdoqv276LYWgwm4J52xGORxhIfLOC8+VmDfdLuQf3k7nDQj9cVWeL2TEdJAM9TsyFQWqkvdAfi+MsLgjJYj7HcIyRP83prsLYawJVG2sZxWxUKDmYdzEocyhuhmkxvmxTC9TSZOjpNK+tBNVRESfvPO+0RUPSLimGUZI+MyssRKg7GUmE9qtmYrouyhdTTvXsXzc3bIIT+w4/9+E7euhXwdo6wVTPJlaUFG0ZZEb0i6NBw33h8SJEAWqVK8nwG2QLH2839LDpcGBGkmQoIgISij6m9NW0FZ5sPiTsAEzxOsy3PWoDLzj9G409fYOQrBRjEN7zs7PjGOIGT2R2qRuJ/V1qrZCsbDLE+BJLVvqUhWDBURB7ALQqSV2MjdCv10M2P1ENRb/MWGOvTq+6v1QO4hlTKow5H2hmRSNiKe9zBVwQ55DBxL5Vi8kvtnUzV8gZbaZQssor2YWuKxKoPYEauXP2sTFU5rE5Kht+Hr4CNDTinOUWophbMABLZPYty/nHq5EbfEXdVjPhVRDZ+tI/rQi74W88sN6XMc/yByWkqFTuaXh6hIEz8Jc0UXU8y47QiI1tujJB9KHq1zOufvW62syJ16KxP9t303FlVQCXgk0gQYUq8IkQSk=

      deploy:
        - provider: script
          skip_cleanup: true
          script: node scripts/deploy Production
          on:
            branch: master


# Disable "Build pushed pull requests"
