dist: trusty
sudo: required
language: node_js
node_js:
  - node
branches:
  except:
  - gh-pages
notifications:
  email: false
services:
  - docker

jobs:
  include:
    - stage: Build
      name: "Build Docker Images"
      install: cd scripts && npm ci && cd ..
      script: node scripts/build
      env:
        # DEPLOY_SETTINGS_JSON='{"CI":[{"type":"docker","options":{"user":"","pass":""}}]}'
        - secure: d22DceuLH7O13NIVQuizhMmaMHlbkVy9s0l8enLDZFsFH6tHfbxR6yQwX+328qQh/0il2LDkAXfcPLS/kE5vmR1z13WPHbYCBd79Z17ypBnq72lwomvUqsSO2gJG02DD3DQ7p6NZWIDudKejIUSsJd1BZ/zBFojBAL9XtrwgGmfIAkOPNjIt5RTZCYitLBdeYk5ZcV+f/0gzAq1d9IxJSDLMO9WGHTyUadXLeTaVYcdBib6O9hhok+n/ZV6c7nCir/HoQf7c3/AmtS07pKM/ctYJ86PqrUZ16L8vLeG239xIG3DGor7YtA9YNsveu92YnRaYuUdx463JVomycu6GO2rvOP6m0cZ1gczi9BnaH1ldpUdOISgIFv5MoDkXkfXqIqfkc2LdCciHuoGRu854AI2Bf/6EU5yztK9SCyDtidI7528/dxoJq9KkgnxvDiRpVlzYkx/7TNRR3md3IOkRj82FqwzhrB2U+ZBNdMLnvNdreES918auRa2xNPDVJ4sMwvU05Y/BoGuHFu4LeDlVYkERC1IYrOGDzapXIhmvXBlD3zviJpcARtL6IRySegCwi8fsyVVXkZE0GZZo2DEEUSH9e/PLjU/0/IIdOczIRq3J1XmoL8jePWJzVLMNQzUK2cFd3Bkqxvpo4xCn8G4cocru786rG8zwMofvJ2aAt9A=

    - stage: Test
      name: "Unit Tests"
      env:
        - image_tag=peyk/federation:unstable-solution
      script: echo ToDo

    - stage: Deploy
      name: "Deploy"
      script: skip
      install:
        - cd scripts && npm ci && cd ..
        - docker pull peyk/client-server:unstable
      env:
        # DEPLOY_SETTINGS_JSON='{"Production":[
        #   {"type":"docker","options":{"source":"peyk/client-server:unstable","target":"peyk/client-server","user":"","pass":""}},
        #   {"type":"heroku","options":{"app":"peyk-client-server","source":"peyk/client-server","dyno":"web","user":"","token":""}}
        # ]}'
        - secure: QoNNRGeirWvSQvFKuJMMssXfhDzOjylgwsivmaNDjL4Auo0o4dq39Ex+Ku51qD5gcw+qf8TyIXl+b1J4BFDiwz/9QfyAgBGIwlFqk1nHUjeaR45wNeANLSBmOany71F/tGgg7Nzg1SOpoxkEWm6tpI9/ZfraImXEibcLJnFu4KXWNshM2DA1m2EYinbIZqBm5x88AIccsnkTcuK2TEmKJluN8sqkoB28yBPNWlanYlPa6/jmPHswnawl14ayCGvqwKaVMrNcQ6sdeAaGKZZR6AFb2DPsewsubC2xt68hH0zg/qHNHes5HKBzEqw/lfgf3c82JzEdr20tJioyEWmrAc5WIocA8U3hrXZsjptyLN1Myfqyl76GkbwUVfDa1jNorAMIk4qz1f4OfEUM0cCfX1uiMkLjj21LQhrZ6WSArFjsbpoyheIkj+6mo2nrWAQ4wGFusDM6OkeFn/D9AdbiJSHfW5G7fknSD2yNM0EK0KFuEYVuHOxhy6r9Lqhqs91qBdjwVzp+11aWLS34VBakDxV6ja97vHz4HDe+CkoEOjZwgazDMFmPuSIpTgxsN0z4QCEGAS6r8ld3TNtajr0HC2izF/MLDX2pLfy2uabTJPuY7FFaIpyICzCahMB0NEd48js9m1Xlt23MtnpfIQBGDLF1U8jLW5BDhCx9cNEGCkw=
      deploy:
        - provider: script
          skip_cleanup: true
          script: node scripts/deploy Production
          on:
            branch: master


# Disable "Build pushed pull requests"
