dist: trusty
sudo: required
language: node_js
node_js:
  - node
branches:
  except:
  - gh-pages
notifications:
  email: false
services:
  - docker

jobs:
  include:
    - stage: Build
      name: "Build Docker Images"
      install: cd scripts && npm ci && cd ..
      script: node scripts/build
      env:
        # DEPLOY_SETTINGS_JSON='{"CI":[{"type":"docker","options":{"user":"","pass":""}}]}'
        - secure: d22DceuLH7O13NIVQuizhMmaMHlbkVy9s0l8enLDZFsFH6tHfbxR6yQwX+328qQh/0il2LDkAXfcPLS/kE5vmR1z13WPHbYCBd79Z17ypBnq72lwomvUqsSO2gJG02DD3DQ7p6NZWIDudKejIUSsJd1BZ/zBFojBAL9XtrwgGmfIAkOPNjIt5RTZCYitLBdeYk5ZcV+f/0gzAq1d9IxJSDLMO9WGHTyUadXLeTaVYcdBib6O9hhok+n/ZV6c7nCir/HoQf7c3/AmtS07pKM/ctYJ86PqrUZ16L8vLeG239xIG3DGor7YtA9YNsveu92YnRaYuUdx463JVomycu6GO2rvOP6m0cZ1gczi9BnaH1ldpUdOISgIFv5MoDkXkfXqIqfkc2LdCciHuoGRu854AI2Bf/6EU5yztK9SCyDtidI7528/dxoJq9KkgnxvDiRpVlzYkx/7TNRR3md3IOkRj82FqwzhrB2U+ZBNdMLnvNdreES918auRa2xNPDVJ4sMwvU05Y/BoGuHFu4LeDlVYkERC1IYrOGDzapXIhmvXBlD3zviJpcARtL6IRySegCwi8fsyVVXkZE0GZZo2DEEUSH9e/PLjU/0/IIdOczIRq3J1XmoL8jePWJzVLMNQzUK2cFd3Bkqxvpo4xCn8G4cocru786rG8zwMofvJ2aAt9A=

    - stage: Test
      name: "Unit Tests"
      env:
        - image_tag=peyk/federation:unstable-solution
      script: echo ToDo

    - stage: Deploy
      name: "Deploy"
      script: skip
      install:
        - cd scripts && npm ci && cd ..
        - docker pull peyk/federation:unstable
      env:
        # DEPLOY_SETTINGS_JSON='{"Production":[
        #   {"type":"docker","options":{"source":"peyk/federation:unstable","target":"peyk/federation","user":"","pass":""}},
        #   {"type":"heroku","options":{"app":"peyk-federation","source":"peyk/federation","dyno":"web","user":"","token":""}}
        # ]}'
        - secure: KT208p1fcR1gYLMbOsubGnkOpzUU/vrvrhwkOZ8JmAjpwHodSIUMrPrZv+k2ayNeM+rjmz7JipK/Uunu+CZhdtHSTejsYOWp4Mn8lgBq0k3a6tnXzm+dBMDjJ/ZtyNenxNUxLyN3GZEN7cDY7B4m/NRkj1fUNfgK7eDkr2DoaYIMGIyedfKDTZEhejEY4aL4wyTwmEAC3UWIJRNhiVJWRea3efzntXbDT+964X38j8TDHlISCWsVC9VecM2KcXjscDaaqHxxBb5UQ/UjbiCRiJiRHKmp0lKcvqCRAPEqTeH2C64NVE6qiBpf6RFPQsIuMBZqgVreymo1nx7bTMNhPE6e28BL57JvR9P2FAzpDiXh/qrpnzQFmlDMZ5DDl7fIZ0A4AMgyd8LiP9hO7MhoDgIlU5JwJTO/FGnICCKR71kZwDfm7+eOCY7hpdFp37WMQ6MgjkB4egSxK8txmHs50LMC4jGyIjfM0yj6As3CcbX+uT3VqLBkh+wY2gyi5e8RbR2IllzwkQtg8BnuBXpOdKsqnf8sqLGrsAx7HO2LaFJcQ+NPGQTi6kjbShHr+QV5lFFOEqELkrCKp9XMmteoBhaFYguGRoGuUuNvCHjGcSM51zD+Cq6vdQNdy80Xtj9REBJu9JfX99rkw1PXyf5ChToh9l8feeUUrhwLK/bGJmY=

      deploy:
        - provider: script
          skip_cleanup: true
          script: node scripts/deploy Production
          on:
            branch: master


# Disable "Build pushed pull requests"
